select * from customer limit 20 ;

-- Q1. What is the total revenue generated by male vs female customers ? (Revenue Split by gender)

select gender, SUM(purchase_amount) as total_revenue
from customer
group by gender
order by 2 desc ;

-- Q2. Which customers used a discount bill but still spent more than the average purchase amount ?

select customer_id, purchase_amount from customer 
where discount_applied = 'Yes' and purchase_amount > (select round(avg(purchase_amount),3) from customer) ;

-- Q3. Which are the top 5 products with the highest average review rating ?

select item_purchased, round(avg(review_rating)::numeric,2) as average_review_rating
from customer
group by item_purchased
order by average_review_rating desc
limit 5 ;

-- Q4. Compare the average purchase amounts between Standard and Express shipping ?

select shipping_type, round(avg(purchase_amount),3) as average_purchase_amount
from customer
where shipping_type IN ('Standard','Express')
group by shipping_type ;

-- Q5. do subscribed customers spend more ? compare avg spend, total revenue b/w subs and non-subs ?

select subscription_status,
	   count(customer_id) as total_customers,
	   round(avg(purchase_amount),2) as average_spend,
	   round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by 2,3 desc ;

-- Q6. which 5 products have highest percentage of purchases with discounts applied ?

SELECT 
    item_purchased,
    COUNT(*) AS total_count,
    COUNT(*) FILTER (WHERE discount_applied = 'Yes') AS discounted_count,
    -- COUNT(*) FILTER (WHERE discount_applied = 'No') AS non_discounted_count,
    ROUND(
        COUNT(*) FILTER (WHERE discount_applied = 'Yes') * 100.0 
        / COUNT(*), 2
    ) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;

Approach 2:
-----------

SELECT 
    item_purchased,
    COUNT(*) AS total_count,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_count,
	-- SUM(CASE WHEN discount_applied = 'No' THEN 1 ELSE 0 END) AS non_discounted_count,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 2
    ) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;

-- Q7. Segment customers into new, loyal, returning based on thier previous purchases and show thier count across each segment ?

WITH customer_type as (
select customer_id, previous_purchases,
	case when previous_purchases = 1 then 'New'
		 when previous_purchases between 2 and 10 then 'Returning'
		 else 'Loyal'
	end as customer_segment
from 
	customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment


-- Q8. What are the top 3 most purchased products under each category ?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders,
		ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT *   
FROM item_counts
WHERE item_rank <= 3;

/*
"First, I aggregate the data at category and product level to get total orders.
Then I use a window function to rank products within each category based on order count. 
Finally, I filter to get the top 3 products per category."

1. Aggregate → GROUP BY
2. Rank → WINDOW FUNCTION
3. Filter → TOP N

ROW_NUMBER ensures exactly N rows per group, whereas RANK or DENSE_RANK can return more rows in case of ties
*/


-- Q9. Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe ?

select subscription_status,
	   count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subsciption_status ;


-- Q10. Revenue contribution for each age group ?

select * from customer

select age_group,
	   sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc









